# Generated by Django 4.1.10 on 2025-06-15 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('farm_type', models.CharField(choices=[('mixed', 'Mixed'), ('livestock', 'Livestock'), ('crop', 'Crop'), ('dairy', 'Dairy'), ('poultry', 'Poultry')], default='mixed', max_length=20)),
                ('size', models.CharField(choices=[('small', 'Small (< 50 acres)'), ('medium', 'Medium (50-500 acres)'), ('large', 'Large (> 500 acres)')], default='medium', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('total_area', models.DecimalField(decimal_places=2, help_text='Total area in acres', max_digits=10)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('worker', 'Worker'), ('viewer', 'Viewer')], default='worker', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('farm', 'user')},
            },
        ),
    ]
