# Generated by Django 4.1.10 on 2025-06-15 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='users',
            field=models.ManyToManyField(related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
    ]
