# Generated by Django 4.2.7 on 2026-01-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='users',
        ),
    ]
