# Generated by Django 4.2.7 on 2026-03-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_remove_farm_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('worker', 'Worker'), ('viewer', 'Viewer')], max_length=20)),
                ('menu_key', models.CharField(choices=[('dashboard', 'Dashboard'), ('animals', 'Animals'), ('crops', 'Crops'), ('tasks', 'Tasks'), ('inventory', 'Inventory'), ('expenses', 'Expenses'), ('reports', 'Reports'), ('settings', 'Settings')], max_length=30)),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_menu_permissions', to='farms.farm')),
            ],
            options={
                'unique_together': {('farm', 'role', 'menu_key')},
            },
        ),
        migrations.CreateModel(
            name='UserMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(choices=[('dashboard', 'Dashboard'), ('animals', 'Animals'), ('crops', 'Crops'), ('tasks', 'Tasks'), ('inventory', 'Inventory'), ('expenses', 'Expenses'), ('reports', 'Reports'), ('settings', 'Settings')], max_length=30)),
                ('can_view', models.BooleanField(blank=True, null=True)),
                ('can_create', models.BooleanField(blank=True, null=True)),
                ('can_edit', models.BooleanField(blank=True, null=True)),
                ('can_delete', models.BooleanField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_menu_permissions', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('farm', 'user', 'menu_key')},
            },
        ),
    ]
