# Generated by Django 4.2.7 on 2026-08-08 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_rolemenupermission_usermenupermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='farm',
            name='unit_system',
            field=models.CharField(choices=[('imperial', 'Imperial'), ('metric', 'Metric')], default='metric', max_length=10),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_type',
            field=models.CharField(choices=[('mixed', 'Mixed'), ('livestock', 'Livestock'), ('crop', 'Crop'), ('dairy', 'Dairy'), ('poultry', 'Poultry'), ('aquaculture', 'Aquaculture'), ('orchard', 'Orchard'), ('vineyard', 'Vineyard'), ('apiary', 'Apiary'), ('greenhouse', 'Greenhouse'), ('hydroponics', 'Hydroponics'), ('nursery', 'Nursery'), ('forestry', 'Forestry'), ('horticulture', 'Horticulture'), ('pastoral', 'Pastoral'), ('agroforestry', 'Agroforestry'), ('other', 'Other')], default='mixed', max_length=30),
        ),
        migrations.AlterField(
            model_name='farm',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='farm',
            name='total_area',
            field=models.DecimalField(decimal_places=2, help_text='Total farm area', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rolemenupermission',
            name='menu_key',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('animals', 'Animals'), ('crops', 'Crops'), ('tasks', 'Tasks'), ('inventory', 'Inventory'), ('expenses', 'Expenses'), ('reports', 'Reports'), ('settings', 'Settings'), ('health', 'Health Alerts'), ('analytics', 'Analytics'), ('subscription', 'Subscription')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usermenupermission',
            name='menu_key',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('animals', 'Animals'), ('crops', 'Crops'), ('tasks', 'Tasks'), ('inventory', 'Inventory'), ('expenses', 'Expenses'), ('reports', 'Reports'), ('settings', 'Settings'), ('health', 'Health Alerts'), ('analytics', 'Analytics'), ('subscription', 'Subscription')], max_length=30),
        ),
        migrations.CreateModel(
            name='FarmCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('animal_type', 'Animal Type'), ('production_type', 'Production Type'), ('crop_type', 'Crop Type'), ('crop_stage', 'Crop Growth Stage'), ('task_category', 'Task Category'), ('inventory_category', 'Inventory Category'), ('expense_category', 'Expense Category'), ('revenue_source', 'Revenue Source'), ('unit', 'Unit of Measurement')], max_length=30)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='farms.farm')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'unique_together': {('farm', 'category_type', 'value')},
            },
        ),
    ]
