# Generated by Django 4.2.7 on 2026-08-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_farm_currency_farm_unit_system_alter_farm_farm_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='currency_symbol',
            field=models.CharField(default='₦', max_length=10),
        ),
    ]
