# Generated by Django 4.2.7 on 2026-08-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_farm_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='logo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
