# Generated by Django 4.2.7 on 2026-08-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_farm_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='rolemenupermission',
            name='menu_key',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('animals', 'Animals'), ('crops', 'Crops'), ('tasks', 'Tasks'), ('inventory', 'Inventory'), ('expenses', 'Expenses'), ('sales', 'Sales & Income'), ('reports', 'Reports'), ('settings', 'Settings'), ('health', 'Health Alerts'), ('analytics', 'Analytics'), ('subscription', 'Subscription')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usermenupermission',
            name='menu_key',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('animals', 'Animals'), ('crops', 'Crops'), ('tasks', 'Tasks'), ('inventory', 'Inventory'), ('expenses', 'Expenses'), ('sales', 'Sales & Income'), ('reports', 'Reports'), ('settings', 'Settings'), ('health', 'Health Alerts'), ('analytics', 'Analytics'), ('subscription', 'Subscription')], max_length=30),
        ),
    ]
