# Generated by Django 4.2.7 on 2026-08-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_alter_farm_options_alter_rolemenupermission_menu_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemenupermission',
            name='menu_key',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('animals', 'Animals'), ('crops', 'Crops'), ('tasks', 'Tasks'), ('inventory', 'Inventory (Main Menu)'), ('inventory-overview', '↳ Inventory: Overview'), ('inventory-audits', '↳ Inventory: Audits'), ('inventory-costs', '↳ Inventory: Cost Analysis'), ('expenses', 'Expenses'), ('sales', 'Sales & Income'), ('reports', 'Reports'), ('health', 'Health Alerts'), ('analytics', 'Analytics (Main Menu)'), ('analytics-forecasting', '↳ Analytics: Demand Forecasting'), ('analytics-animals', '↳ Analytics: Animal Productivity'), ('analytics-financial', '↳ Analytics: Financial Overview'), ('analytics-crops', '↳ Analytics: Crop Analytics'), ('settings', 'Settings'), ('subscription', 'Subscription')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usermenupermission',
            name='menu_key',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('animals', 'Animals'), ('crops', 'Crops'), ('tasks', 'Tasks'), ('inventory', 'Inventory (Main Menu)'), ('inventory-overview', '↳ Inventory: Overview'), ('inventory-audits', '↳ Inventory: Audits'), ('inventory-costs', '↳ Inventory: Cost Analysis'), ('expenses', 'Expenses'), ('sales', 'Sales & Income'), ('reports', 'Reports'), ('health', 'Health Alerts'), ('analytics', 'Analytics (Main Menu)'), ('analytics-forecasting', '↳ Analytics: Demand Forecasting'), ('analytics-animals', '↳ Analytics: Animal Productivity'), ('analytics-financial', '↳ Analytics: Financial Overview'), ('analytics-crops', '↳ Analytics: Crop Analytics'), ('settings', 'Settings'), ('subscription', 'Subscription')], max_length=30),
        ),
    ]
