# Generated by Django 4.2.7 on 2026-04-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_rolemenupermission_usermenupermission'),
        ('inventory', '0002_alter_inventorytransaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_monthly_usage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_monthly_usage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_monthly_usage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usage_trend', models.CharField(choices=[('stable', 'Stable'), ('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('seasonal', 'Seasonal')], default='stable', max_length=20)),
                ('seasonality_factor', models.DecimalField(decimal_places=2, default=1.0, help_text='Seasonality multiplier', max_digits=5)),
                ('forecasted_monthly_demand', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('optimal_reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('optimal_order_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('forecast_accuracy', models.DecimalField(decimal_places=2, default=0, help_text='Accuracy percentage', max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data_points', models.IntegerField(default=0, help_text='Number of historical data points used')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='farms.farm')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecast', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name_plural': 'Demand Forecasts',
            },
        ),
        migrations.CreateModel(
            name='SupplierPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('avg_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lowest_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('highest_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage', max_digits=5)),
                ('quality_rating', models.DecimalField(decimal_places=1, default=5.0, help_text='1-10 scale', max_digits=3)),
                ('reliability_grade', models.CharField(choices=[('excellent', 'Excellent (95%+)'), ('good', 'Good (85-95%)'), ('fair', 'Fair (70-85%)'), ('poor', 'Poor (<70%)')], default='good', max_length=20)),
                ('total_orders', models.IntegerField(default=0)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_performance', to='farms.farm')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_metrics', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name_plural': 'Supplier Performance',
                'unique_together': {('farm', 'supplier_name', 'item')},
            },
        ),
    ]
