# Generated by Django 4.2.7 on 2026-08-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_demandforecast_supplierperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
