# Generated by Django 4.2.7 on 2026-08-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryaudit',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for multi-day audit range', null=True),
        ),
    ]
