# Generated by Django 4.2.7 on 2026-04-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvest',
            options={},
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='notes',
        ),
        migrations.AlterField(
            model_name='harvest',
            name='quality_grade',
            field=models.CharField(blank=True, choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], max_length=10),
        ),
        migrations.CreateModel(
            name='WeatherImpactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_date', models.DateField()),
                ('impact_type', models.CharField(choices=[('drought', 'Drought'), ('flood', 'Flood'), ('frost', 'Frost'), ('excessive_heat', 'Excessive Heat'), ('wind_damage', 'Wind Damage'), ('hail', 'Hail'), ('pest_outbreak', 'Pest Outbreak'), ('disease', 'Disease'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('minor', 'Minor (1-10% loss)'), ('moderate', 'Moderate (10-25% loss)'), ('severe', 'Severe (25-50% loss)'), ('critical', 'Critical (50%+ loss)')], max_length=20)),
                ('estimated_yield_loss', models.DecimalField(decimal_places=2, default=0, help_text='Percentage', max_digits=5)),
                ('estimated_financial_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('recovery_actions', models.TextField(blank=True)),
                ('recovery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_recovery_yield', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of original', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_impacts', to='crops.crop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FertilizerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_type', models.CharField(help_text='e.g., NPK 10-10-10', max_length=100)),
                ('recommended_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(default='lbs', max_length=50)),
                ('application_timing', models.CharField(help_text='When to apply', max_length=200)),
                ('expected_yield_increase', models.DecimalField(decimal_places=2, default=0, help_text='Percentage', max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('actual_quantity_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_additional_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_recommendations', to='crops.crop')),
            ],
            options={
                'verbose_name_plural': 'Fertilizer Recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropYieldAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_yield', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_yield', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yield_unit', models.CharField(default='lbs/acre', max_length=50)),
                ('water_provided', models.DecimalField(blank=True, decimal_places=2, help_text='Inches or mm', max_digits=8, null=True)),
                ('fertilizer_applied', models.DecimalField(blank=True, decimal_places=2, help_text='lbs or kg', max_digits=8, null=True)),
                ('disease_severity', models.IntegerField(default=0, help_text='0-100 scale')),
                ('pest_damage', models.IntegerField(default=0, help_text='0-100 scale')),
                ('yield_per_dollar_invested', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('roi_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('yield_efficiency', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of expected', max_digits=5)),
                ('optimization_recommendations', models.TextField(blank=True, help_text='AI generated recommendations')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_analysis', to='crops.crop')),
            ],
            options={
                'verbose_name_plural': 'Crop Yield Analysis',
            },
        ),
    ]
