# Generated by Django 4.2.7 on 2026-08-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_alter_harvest_options_remove_harvest_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='crop_lifecycle',
            field=models.CharField(choices=[('annual', 'Annual'), ('perennial', 'Perennial'), ('biennial', 'Biennial')], default='annual', max_length=20),
        ),
        migrations.AlterField(
            model_name='crop',
            name='stage',
            field=models.CharField(default='planning', max_length=50),
        ),
        migrations.AlterField(
            model_name='cropactivity',
            name='activity_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cropyieldanalysis',
            name='yield_unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='growthstage',
            name='stage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
