# Generated by Django 4.2.7 on 2026-08-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='discount_badge',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_animals',
            field=models.IntegerField(default=99999),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_crops',
            field=models.IntegerField(default=99999),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_farms',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.IntegerField(default=14),
        ),
    ]
