[phases.setup]
nixPkgs = ["...", "libpq"]
aptPkgs = ["...", "libpq-dev"]

[phases.build]
cmds = [
    "...",
    "python manage.py migrate --noinput",
    "python create_superuser.py",
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn terra_track.wsgi --bind 0.0.0.0:$PORT"
