# Generated by Django 4.2.7 on 2026-04-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_vaccination_healthalert_breedingcalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_type', models.CharField(choices=[('milk', 'Milk'), ('eggs', 'Eggs'), ('wool', 'Wool'), ('meat', 'Meat'), ('honey', 'Honey'), ('manure', 'Manure'), ('other', 'Other')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(help_text='e.g. liters, pieces, kg', max_length=50)),
                ('recorded_date', models.DateField()),
                ('quality_grade', models.CharField(blank=True, choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], default='A', max_length=10)),
                ('market_price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('feed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='animals.animal')),
            ],
            options={
                'verbose_name_plural': 'Production Records',
                'ordering': ['-recorded_date'],
            },
        ),
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('mated', 'Mated'), ('pregnant', 'Pregnant'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='planned', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('number_of_offspring', models.IntegerField(default=0)),
                ('healthy_offspring', models.IntegerField(default=0)),
                ('stillborn', models.IntegerField(default=0)),
                ('genetics_notes', models.TextField(blank=True, help_text='Genetic traits, inheritance notes')),
                ('birth_weights', models.JSONField(blank=True, default=dict, help_text='Map of offspring IDs to birth weights')),
                ('veterinary_complications', models.TextField(blank=True)),
                ('post_delivery_care', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breeding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='animals.breedingcalendar')),
                ('dam_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Dam_offspring', to='animals.animal')),
                ('sire_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sired_offspring', to='animals.animal')),
            ],
            options={
                'verbose_name_plural': 'Breeding Records',
            },
        ),
        migrations.CreateModel(
            name='AnimalProductionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month_production', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_monthly_production', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('highest_monthly_production', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('year_to_date_production', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_feed_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('feed_conversion_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('production_efficiency', models.DecimalField(decimal_places=2, default=0, help_text='Percentage', max_digits=5)),
                ('breeding_success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('health_score', models.DecimalField(decimal_places=1, default=5.0, help_text='1-10 scale', max_digits=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_metrics', to='animals.animal')),
            ],
            options={
                'verbose_name_plural': 'Animal Production Metrics',
            },
        ),
    ]
