# Generated by Django 4.2.7 on 2026-08-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_productionrecord_breedingrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='production_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='vaccine_type',
            field=models.CharField(max_length=50),
        ),
    ]
