# Generated by Django 4.2.7 on 2026-08-09 05:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_farm_currency_farm_unit_system_alter_farm_farm_type_and_more'),
        ('inventory', '0004_alter_inventoryitem_category'),
        ('animals', '0004_alter_animal_animal_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_mixes', to='farms.farm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='deduct_from_inventory',
            field=models.BooleanField(default=True, help_text='Should feed be deducted from inventory stock'),
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='end_date',
            field=models.DateField(blank=True, help_text='Recurring daily feed schedule end date', null=True),
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedrecord',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_consumption', to='animals.animal'),
        ),
        migrations.AlterField(
            model_name='feedrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='RecurringFeedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=100)),
                ('feed_type', models.CharField(blank=True, max_length=100)),
                ('daily_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('deduct_from_inventory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='animals.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_feed_schedules', to='farms.farm')),
                ('feed_mix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_schedules', to='animals.feedmix')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedMixItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Proportion percentage (e.g. 60.00)', max_digits=5)),
                ('feed_mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='animals.feedmix')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_mix_components', to='inventory.inventoryitem')),
            ],
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='feed_mix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_records', to='animals.feedmix'),
        ),
    ]
