# Generated by Django 4.2.7 on 2026-08-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_feedmix_feedrecord_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Initial purchase / acquisition price', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('injured', 'Injured'), ('pregnant', 'Pregnant'), ('nursing', 'Nursing'), ('quarantined', 'Quarantined'), ('sold', 'Sold'), ('archived', 'Archived')], default='healthy', max_length=20),
        ),
    ]
