# Generated by Django 4.2.7 on 2026-01-03 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('feed', 'Feed'), ('labor', 'Labor'), ('equipment', 'Equipment'), ('utilities', 'Utilities'), ('seeds', 'Seeds'), ('veterinary', 'Veterinary'), ('fuel', 'Fuel'), ('maintenance', 'Maintenance'), ('insurance', 'Insurance'), ('taxes', 'Taxes'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', models.CharField(max_length=200)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check')], max_length=20)),
                ('receipt', models.FileField(blank=True, upload_to='receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='farms.farm')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('feed', 'Feed'), ('labor', 'Labor'), ('equipment', 'Equipment'), ('utilities', 'Utilities'), ('seeds', 'Seeds'), ('veterinary', 'Veterinary'), ('fuel', 'Fuel'), ('maintenance', 'Maintenance'), ('insurance', 'Insurance'), ('taxes', 'Taxes'), ('other', 'Other')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(blank=True, null=True)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='farms.farm')),
            ],
            options={
                'unique_together': {('farm', 'category', 'year', 'month')},
            },
        ),
    ]
