# Generated by Django 4.2.7 on 2026-04-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_rolemenupermission_usermenupermission'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('animal_products', 'Animal Products'), ('crop_sales', 'Crop Sales'), ('equipment_rental', 'Equipment Rental'), ('services', 'Services'), ('government_subsidy', 'Government Subsidy'), ('grants', 'Grants'), ('other', 'Other')], max_length=30)),
                ('item_sold', models.CharField(help_text='e.g., Milk, Corn, Eggs', max_length=200)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buyer', models.CharField(blank=True, max_length=200)),
                ('quality_grade', models.CharField(blank=True, choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='farms.farm')),
            ],
            options={
                'verbose_name_plural': 'Revenues',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DebtManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(max_length=200)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disbursement_date', models.DateField()),
                ('due_date', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid_off', 'Paid Off'), ('defaulted', 'Defaulted')], default='active', max_length=20)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('next_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], max_length=20)),
                ('number_of_payments', models.IntegerField(blank=True, null=True)),
                ('payments_completed', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='farms.farm')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly'), ('quarter', 'Quarterly')], max_length=10)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('animal_product_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('crop_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('feed_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labor_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('equipment_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, help_text='Percentage', max_digits=5)),
                ('roi', models.DecimalField(decimal_places=2, default=0, help_text='Return on Investment %', max_digits=5)),
                ('profit_trend', models.CharField(blank=True, choices=[('increasing', 'Increasing'), ('stable', 'Stable'), ('decreasing', 'Decreasing')], max_length=20, null=True)),
                ('expense_trend', models.CharField(blank=True, choices=[('increasing', 'Increasing'), ('stable', 'Stable'), ('decreasing', 'Decreasing')], max_length=20, null=True)),
                ('budgeted_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_variance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_analysis', to='farms.farm')),
            ],
            options={
                'verbose_name_plural': 'Financial Analysis',
                'unique_together': {('farm', 'period_type', 'year', 'month', 'quarter')},
            },
        ),
    ]
