# Generated by Django 4.2.7 on 2026-08-08 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_crop_crop_lifecycle_alter_crop_stage_and_more'),
        ('animals', '0004_alter_animal_animal_type_and_more'),
        ('expenses', '0002_revenue_debtmanagement_financialanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='linked_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_expenses', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='expense',
            name='linked_crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_expenses', to='crops.crop'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='source',
            field=models.CharField(max_length=50),
        ),
    ]
